### ISSUE TITLE
Missing file/incorrect link to CONTRIBUTING

### ISSUE THREAD

**Issue by clausmullie** [AjuntamentdeBarcelona/innovative-procurement-bcn-en#3]
Last sentence in README has a hyperlink in CONTRIBUTING which gives a 404

**Comment by clausmullie** [comment]
Issue replicates in:
/ict-procurement-bcn-ca
/ict-procurement-bcn-en
/innovative-procurement-bcn-en
/tech-practices-code-bcn-ca
/tech-sovereignty-manifesto-bcn-en
/digital-service-standards-bcn-ca

Have you considered linking back to CONTRIBUTING.adoc in your [ethical digital standards site](https://github.com/AjuntamentdeBarcelona/ethical-digital-standards-site) from each of the sub-repos to avoid having multiple instances of the same file and thus requiring more maintenance?

**Comment by imingueza** [comment]
Thank you for your contribution. You are right, the first README version pointed to a local CONTRIBUTION file, but the free software project manager realized that was more efficient to maintain only one CONTRIBUTING file on [ethical digital standards site ](https://github.com/AjuntamentdeBarcelona/ethical-digital-standards-site) and the other READMEs make reference to this file.

**Comment by clausmullie** [comment]
Great! Just one note - you have an instance of the CONTRIBUTING file in Catalan [here](https://github.com/AjuntamentdeBarcelona/tech-sovereignty-guide-bcn-ca/blob/master/CONTRIBUTING.adoc) which you may want to add to the ethical digital standards site so that you have both 'master' files there which you can link back to.

**Comment by imingueza** [comment]
> 
> 
> Great! Just one note - you have an instance of the CONTRIBUTING file in Catalan [here](https://github.com/AjuntamentdeBarcelona/tech-sovereignty-guide-bcn-ca/blob/master/CONTRIBUTING.adoc) which you may want to add to the ethical digital standards site so that you have both 'master' files there which you can link back to.

In this specific case, we choose to maintain a single version of the file. We suppose that people that will  contribute has the enough English reading level for understand the English contribution file.
